# Generated by Django 5.0.6 on 2025-07-22 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0018_alter_product_thumbnail"),
        ("project", "0008_alter_projectuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("impressions", models.IntegerField(default=0)),
                (
                    "impression_revenue",
                    models.DecimalField(decimal_places=18, default=0, max_digits=30),
                ),
                ("sales_count", models.IntegerField(default=0)),
                ("rentals_count", models.IntegerField(default=0)),
                (
                    "royalty_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=40),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_record",
                "unique_together": {
                    ("project", "product", "period_start", "period_end")
                },
            },
        ),
    ]
