# Generated by Django 5.0.6 on 2025-03-02 17:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_projectuser_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectuser",
            unique_together={("project", "user")},
        ),
    ]
