FROM node:18-alpine

# Install additional dependencies if needed
RUN apk add --no-cache bash

WORKDIR /app

COPY package.json ./

# Install Node.js dependencies
RUN npm install --force

# Set the default command
CMD ["npm", "start"]
