# Generated by Django 5.0.6 on 2025-06-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='name',
        ),
    ]
