# Generated by Django 5.0.6 on 2025-06-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_remove_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
