# Generated by Django 5.0.6 on 2025-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_add_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('google_ads', 'Google Ads'), ('facebook', 'Facebook'), ('amazon', 'Amazon'), ('tiktok', 'TikTok')], max_length=50),
        ),
    ]
