# Generated by Django 5.0.6 on 2025-07-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0008_alter_source_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="platform",
            field=models.CharField(
                choices=[
                    ("youtube", "YouTube"),
                    ("google_ads", "Google Ads"),
                    ("facebook", "Facebook"),
                    ("amazon", "Amazon"),
                    ("tiktok", "TikTok"),
                    ("twitch", "Twitch"),
                ],
                max_length=50,
            ),
        ),
    ]
