FROM python:3.11

WORKDIR /backend

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD ["sh", "-c", "python manage.py makemigrations user project && python manage.py migrate && python manage.py loaddata initial_data.json && exec gunicorn --bind 0.0.0.0:8000 --workers 3 royaltyx.wsgi:application --timeout 120"]