FROM python:3.11

WORKDIR /backend

COPY requirements.txt ./

RUN pip install --upgrade pip setuptools wheel && \
    pip install -r requirements.txt

COPY . .

CMD ["sh", "-c", "python manage.py migrate && exec python manage.py runserver 0.0.0.0:8000"]
