# Generated by Django 5.0.6 on 2025-07-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_is_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("links", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "banner",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
