# Generated by Django 5.0.6 on 2025-03-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_period_end_report_period_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='period_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='period_start',
            field=models.DateField(null=True),
        ),
    ]
