# Generated by Django 5.0.6 on 2025-07-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0004_reporttemplates_report_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplates",
            name="colors",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="reporttemplates",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reporttemplates",
            name="layout",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="reporttemplates",
            name="logo_settings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="reporttemplates",
            name="typography",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
