# Generated by Django 5.0.6 on 2025-07-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("subject", models.CharField(max_length=255)),
                ("body_html", models.TextField()),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Email"),
                            ("password_reset", "Password Reset"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "email_template",
            },
        ),
    ]
