# Generated by ChatGPT
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceMilestone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("metric", models.CharField(max_length=20, choices=[
                    ("impressions", "Impressions"),
                    ("sales", "Sales"),
                    ("rentals", "Rentals"),
                    ("views", "Views"),
                    ("downloads", "Downloads"),
                ])),
                ("threshold", models.PositiveIntegerField()),
                ("alert_via_email", models.BooleanField(default=True)),
                ("alert_via_sms", models.BooleanField(default=False)),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="milestones", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "performance_milestone",
            },
        ),
    ]
