# Generated by Django 5.0.6 on 2025-07-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0008_alter_projectuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("symbol", models.CharField(max_length=10)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "db_table": "stock",
                "unique_together": {("project", "symbol")},
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date", models.DateField()),
                ("open", models.DecimalField(decimal_places=2, max_digits=20)),
                ("high", models.DecimalField(decimal_places=2, max_digits=20)),
                ("low", models.DecimalField(decimal_places=2, max_digits=20)),
                ("close", models.DecimalField(decimal_places=2, max_digits=20)),
                ("volume", models.BigIntegerField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "stock_price",
                "unique_together": {("stock", "date")},
            },
        ),
    ]
