# Generated by Django 5.0.6 on 2025-07-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageCustomization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("landing", "Landing"),
                            ("login", "Login"),
                            ("signup", "Signup"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "page_customization",
            },
        ),
    ]
