# Generated by Django 5.0.6 on 2025-04-05 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_imports", "0002_file_file_alter_file_name_alter_file_project"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="file",
            table="file",
        ),
    ]
