# Generated by Django 5.0.6 on 2025-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_imports", "0003_alter_file_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(max_length=255, null=True, upload_to="uploads/"),
        ),
    ]
