# Generated by Django 5.0.6 on 2025-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_impressions_alter_product_payment_window_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="payment_threshold",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
