# Generated by Django 5.0.6 on 2025-03-09 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_productimpressions_period_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="impressions",
        ),
    ]
