# Generated by Django 5.0.6 on 2025-06-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_productimpressions_ecpm"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
