# Generated by Django 5.0.6 on 2025-06-28 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_external_id'),
        ('sources', '0006_source_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.source'),
        ),
    ]
