# Generated by Django 5.0.6 on 2025-07-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_product_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="product_thumbnails/"
            ),
        ),
    ]
