# Generated by Django 5.0.6 on 2025-07-22 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_alter_product_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("image", models.ImageField(upload_to="product_images/", max_length=500)),
                (
                    "project",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="project.project"),
                ),
                (
                    "product",
                    models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to="product.product"),
                ),
            ],
            options={"db_table": "product_image"},
        ),
    ]
