# Generated by Django 5.0.6 on 2025-07-21 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0008_alter_projectuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhiteLabelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(blank=True, max_length=255)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("logo_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(blank=True, max_length=50)),
                ("secondary_color", models.CharField(blank=True, max_length=50)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="white_label_config",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "db_table": "white_label_config",
            },
        ),
    ]
