# Generated by Django 5.0.6 on 2025-07-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addon",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
