# Generated by Codex on 2025-07-21
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0008_user_grace_period_end_user_payment_failure_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affiliate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referral_code", models.CharField(max_length=20, unique=True)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                (
                    "total_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate",
                        to="user.user",
                    ),
                ),
            ],
            options={"db_table": "affiliate"},
        ),
        migrations.CreateModel(
            name="AffiliateReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commission_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="affiliate.affiliate",
                    ),
                ),
                (
                    "referred_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral",
                        to="user.user",
                    ),
                ),
            ],
            options={"db_table": "affiliate_referral"},
        ),
    ]
