# Generated by Django 5.0.6 on 2025-07-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_plan",
            field=models.CharField(
                choices=[("free", "Free"), ("basic", "Basic"), ("premium", "Premium")],
                default="free",
                max_length=10,
            ),
        ),
    ]
