# Generated by Django 5.0.6 on 2025-07-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_user_grace_period_end_user_payment_failure_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cash_app_tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="echeck_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="echeck_routing_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="paypal_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paypal", "PayPal"),
                    ("zelle", "Zelle"),
                    ("cashapp", "Cash App"),
                    ("echeck", "eCheck"),
                    ("wire", "Wire Transfer"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="wire_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="wire_bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="wire_routing_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="zelle_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
