# Generated by Django 5.0.6 on 2025-07-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_user_grace_period_end_user_payment_failure_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "permission",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="user.permission"
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("user", "Permission")
            .objects.get_or_create(
                code="admin_access",
                defaults={"description": "Access admin panel"},
            )
        ),
    ]
