# Generated by Django 5.0.6 on 2025-07-22 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("user", "0009_add_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="add_ons",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="payments.addon"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_item_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
